import { createSlice } from "@reduxjs/toolkit";

const detailsSlice = createSlice({
  name: "details",
  initialState: {
    details: [
      {
        companyname: "Panacea Solutions",
        partneredfor: "Development",
        partneredin: "Code_Yatra",
        contactinfo: "-----",
        email: "info@panaceasolutionnepal.com",
        socials: "https://www.instagram.com/panaceasolutionnepal/",
      },
      {
        companyname: "Github Education",
        partneredfor: "Silver Sponsor",
        partneredin: "Code_Yatra",
        contactinfo: "-----",
        email: "education@github.com (unofficial)",
        socials: "https://www.instagram.com/githubeducation/",
      },
      {
        companyname: "Github Education",
        partneredfor: "Education",
        partneredin: "Code_Yatra",
        contactinfo: "-----",
        email: "education@github.com (unofficial)",
        socials: "https://www.instagram.com/githubeducation/",
      },
      {
        companyname: "Programiz",
        partneredfor: "E-Learning",
        partneredin: "Code_Yatra, Bio_Hackathon",
        contactinfo: "-----",
        email: "app@programiz.com (unofficial)",
        socials: "https://www.instagram.com/_programiz/",
      },
      {
        companyname: "Mero Job",
        partneredfor: "Career",
        partneredin: "Code_Yatra, Sandbox",
        contactinfo: "+977 1 4106700",
        email: "info@merojob.com",
        socials: "https://www.instagram.com/merojob/",
      },
      {
        companyname: "CF Moto",
        partneredfor: "2-Wheeler EV",
        partneredin: "Code_Yatra",
        contactinfo: "-----",
        email: "-----",
        socials: "https://www.instagram.com/cfmoto_nepal/",
      },
      {
        companyname: "Word Camp",
        partneredfor: "Community",
        partneredin: "Code_Yatra",
        contactinfo: "-----",
        email: "-----",
        socials: "https://www.instagram.com/wordcampnepal/",
      },
      {
        companyname: "GDG Kathmandu",
        partneredfor: "Community",
        partneredin: "Code_Yatra, Sandbox",
        contactinfo: "-----",
        email: "-----",
        socials: "https://www.instagram.com/googlefordevs/",
      },
      {
        companyname: "Leapfrog",
        partneredfor: "IT Company",
        partneredin: "Code_Yatra",
        contactinfo: "-----",
        email: "-----",
        socials: "https://www.instagram.com/lftechnology/",
      },
      {
        companyname: "Oglepeek",
        partneredfor: "Gift",
        partneredin: "Code_Yatra",
        contactinfo: "+977 9868956905",
        email: "-----",
        socials: "https://www.instagram.com/oglepeek/",
      },
      {
        companyname: "Accessory Aid",
        partneredfor: "Gift",
        partneredin: "Code_Yatra",
        contactinfo: "-----",
        email: "-----",
        socials: "/",
      },
      {
        companyname: "Ultima Lifestyle",
        partneredfor: "Gift",
        partneredin: "Code_Yatra",
        contactinfo: "01-5313291",
        email: "support@ultima.com.np",
        socials: "https://www.instagram.com/ultima_lifestyle/",
      },
      {
        companyname: "Vionna Jewels",
        partneredfor: "Gift",
        partneredin: "Code_Yatra",
        contactinfo: "-----",
        email: "-----",
        socials: "https://www.instagram.com/vionnajewels/",
      },
      {
        companyname: "Security Pal",
        partneredfor: "Co-Sponsor",
        partneredin: "Sandbox",
        contactinfo: "-----",
        email: "-----",
        socials: "https://www.instagram.com/securitypal.hq/",
      },
      {
        companyname: "MAYA British College",
        partneredfor: "Supporter",
        partneredin: "Sandbox",
        contactinfo: "+977-980190872",
        email: "info@mayabritish.com",
        socials: "https://www.instagram.com/mayabritishcollege/",
      },
      {
        companyname: "AWS Cloud Clubs Nepal",
        partneredfor: "Commuinty",
        partneredin: "Sandbox",
        contactinfo: "-----",
        email: "-----",
        socials: "https://www.instagram.com/awscloudclub.tu/",
      },
      {
        companyname: "GNOME Nepal",
        partneredfor: "Commuinty",
        partneredin: "Sandbox",
        contactinfo: "-----",
        email: "-----",
        socials: "https://www.instagram.com/gnomenepal/",
      },
      {
        companyname: "Sagarmatha IT Club",
        partneredfor: "Commuinty",
        partneredin: "Sandbox",
        contactinfo: "+977-1-5911274",
        email: "info@scst.edu.np",
        socials: "https://www.instagram.com/sagarmathaitclub/",
      },
      {
        companyname: "WorldLink",
        partneredfor: "Internet",
        partneredin: "Sandbox",
        contactinfo: "01-5970050",
        email: "support@worldlink.com.np",
        socials: "https://www.instagram.com/wlinkcommunications/",
      },
      {
        companyname: "Khalti",
        partneredfor: "Finance",
        partneredin: "Sandbox",
        contactinfo: "01-5970017",
        email: "support@khalti.com",
        socials: "https://www.instagram.com/khaltiofficial/",
      },
      {
        companyname: "Machhapuchchhre Bank",
        partneredfor: "Banking",
        partneredin: "Sandbox",
        contactinfo: "01-4528556",
        email: "machbank@mbl.com.np",
        socials: "https://www.instagram.com/machhapuchchhre_bank/",
      },
      {
        companyname: "Treeleaf",
        partneredfor: "AI",
        partneredin: "Sandbox",
        contactinfo: "+977 9863544235",
        email: "info@treeleaf.ai",
        socials: "https://www.instagram.com/treeleafai/",
      },
      {
        companyname: "Anydone",
        partneredfor: "AI",
        partneredin: "Sandbox",
        contactinfo: "-----",
        email: "support@anydone.com",
        socials: "https://www.instagram.com/anydone.us/",
      },
      {
        companyname: "Palm Mind",
        partneredfor: "Technology",
        partneredin: "Sandbox",
        contactinfo: "01-5912155",
        email: "janak.bhattrai@palmmind.com",
        socials: "https://www.instagram.com/palmmind.np/",
      },
      {
        companyname: "Apricot Venture",
        partneredfor: "Digital Display",
        partneredin: "Sandbox",
        contactinfo: "+977-14599507",
        email: "info@apricotventures.biz",
        socials: "https://www.instagram.com/apricotventures/",
      },
      {
        companyname: "Ather",
        partneredfor: "Mobility",
        partneredin: "Sandbox",
        contactinfo: "-----",
        email: "info@atherenergy.com.np",
        socials: "https://www.instagram.com/atherenergy_nepal/",
      },
      {
        companyname: "Himalayan Crystal House",
        partneredfor: "Gift",
        partneredin: "Sandbox",
        contactinfo: "+977 9843805450",
        email: "info@himalayancrystalhouse.com",
        socials: "https://www.instagram.com/himalayancrystalhouse/",
      },
      {
        companyname: "Astrek Climbing Wall",
        partneredfor: "Adventure",
        partneredin: "Sandbox",
        contactinfo: "014519265",
        email: "-----",
        socials: "https://www.instagram.com/climbastrek/?hl=en",
      },
      {
        companyname: "Ultima Lifestyle",
        partneredfor: "Audio",
        partneredin: "Sandbox",
        contactinfo: "01-5313291",
        email: "support@ultima.com.np",
        socials: "https://www.instagram.com/ultima_lifestyle/",
      },
      {
        companyname: "Kumari Job",
        partneredfor: "Title Sponsor",
        partneredin: "Bio_Hackathon",
        contactinfo: " 01-5199600.",
        email: "info@kumarijob.com",
        socials: "https://www.instagram.com/kumari_job/?hl=en",
      },
      {
        companyname: "Github",
        partneredfor: "Gold Sponsor",
        partneredin: "Bio_Hackathon",
        contactinfo: "Portal",
        email: "Portal",
        socials: "https://www.instagram.com/github/?hl=en",
      },
      {
        companyname: "Dora Hack",
        partneredfor: "Silver Sponsor",
        partneredin: "Bio_Hackathon",
        contactinfo: "-----",
        email: "-----",
        socials: "https://www.instagram.com/dorahacks/",
      },
      {
        companyname: "Edusajnal",
        partneredfor: "Media",
        partneredin: "Bio_Hackathon",
        contactinfo: "01-4155052",
        email: "info@edusanjal.com",
        socials: "https://www.instagram.com/edusanjal/?hl=en",
      },
      {
        companyname: "CSIT Association of Nepal",
        partneredfor: "Community",
        partneredin: "Bio_Hackathon",
        contactinfo: "+977-9840298627",
        email: "csitanoffical@gmail.com",
        socials: "https://www.instagram.com/csitan_official/?hl=en",
      },
      {
        companyname: "Sajilo Ride Sharing",
        partneredfor: "Mobility",
        partneredin: "Bio_Hackathon",
        contactinfo: "985-1332765",
        email: "sajilosaathi2022@gmail.com",
        socials: "https://www.instagram.com/sajiloridenp/",
      },
      {
        companyname: "PaperFiles",
        partneredfor: "Stationery",
        partneredin: "Bio_Hackathon",
        contactinfo: "-----",
        email: "-----",
        socials: "https://www.instagram.com/paperfliesnotebooks/?hl=en",
      },
      {
        companyname: "Jyaa Crochet Fashion",
        partneredfor: "Gift",
        partneredin: "Bio_Hackathon",
        contactinfo: "----",
        email: "----",
        socials: "https://www.instagram.com/jyaa_crochet_fashion/",
      },
      {
        companyname: "Hukut",
        partneredfor: "Gift",
        partneredin: "Bio_Hackathon",
        contactinfo: "9801100035",
        email: "hukutorders@gmail.com",
        socials: "https://www.instagram.com/hukutstorenp/",
      },
      {
        companyname: "Commute Agro",
        partneredfor: "Gift",
        partneredin: "Bio_Hackathon",
        contactinfo: "-----",
        email: "-----",
        socials: "https://www.instagram.com/commute_agro/",
      },
      {
        companyname: "Zewelicious",
        partneredfor: "Gift",
        partneredin: "Bio_Hackathon",
        contactinfo: "+9779841507505",
        email: "-----",
        socials: "https://www.instagram.com/zewelicious.np/",
      },
    ],
  },
});

export default detailsSlice.reducer;
